### ISSUE TITLE
Unable to watch for file changes in this large workspace

### ISSUE THREAD

**Issue by darkbasic** [llebout/vscode#2]
I get this every time I start vscode, despite the workspace being very small.
With IntelliJ IDEA I had to install this to get rid of a similar issue: https://github.com/vddvss/fsnotifier-ppc64le
I don't know if it's somehow related.
@vddvss

**Comment by vddvss** [comment]
Hmm, this could be an issue with the inotify watches limit. What's the output of `sysctl fs.inotify.max_user_watches`?

**Comment by darkbasic** [comment]
It's the default value:
```
$ sysctl fs.inotify.max_user_watches
fs.inotify.max_user_watches = 8192
```

Anyway I noticed that after rebooting I no longer have this issue, probably another app was maxing it out?

**Comment by llebout** [comment]
@darkbasic Issue is documented here: https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

Not ppc64le specific.
